CREATE TABLE IF NOT EXISTS triage (
    triage_id SERIAL PRIMARY KEY,
    agent_id INT,
    client_id INT NOT NULL REFERENCES client(client_id),
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    re_conf INT DEFAULT 0,
    mfm_conf INT DEFAULT 0,
    uro_conf INT DEFAULT 0,
    gob_conf INT DEFAULT 0,
    mis_conf INT DEFAULT 0,
    go_conf INT DEFAULT 0,
    doc_id1 INT REFERENCES doctor(doc_id),
    doc_id2 INT REFERENCES doctor(doc_id),
    doc_id3 INT REFERENCES doctor(doc_id),
    agent_notes TEXT,
    sent_to_epic BOOLEAN DEFAULT FALSE,
    epic_sent_date TIMESTAMP
);

INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1881, '2025-10-12 00:28:50', 23, 54, 8, 1, 5, 9, 13, 18, 12, 'HIST: hx of PCOS in 2011; family hx of endometrial cancer | CURR: concern for nausea in pregnancy after exercise; denies foul discharge, but endorses pelvic pain weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2311, '2025-10-12 00:28:50', 3, 23, 49, 4, 19, 2, 14, 19, 9, 'HIST: family hx of endometrial cancer; hx of fibroids in 2015 | CURR: concern for vaginal bulge after exercise; notes nausea in pregnancy that improves with NSAIDs | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1455, '2025-10-12 00:28:50', 24, 4, 19, 7, 34, 12, 11, 16, 7, 'HIST: family hx of ovarian cancer; hx of endometriosis in 2008 | CURR: notes urinary urgency that occurs daily; denies foul discharge, but endorses postcoital bleeding weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2610, '2025-10-12 00:28:50', 7, 13, 8, 16, 46, 10, 11, 16, 19, 'HIST: family hx of breast cancer; prior laparoscopy in 2010 | CURR: concern for leakage after lifting; notes heavy periods that worsens with menses | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2381, '2025-10-12 00:28:50', 7, 36, 2, 5, 33, 17, 13, 18, 14, 'HIST: prior LEEP in 2019; medication: metformin | CURR: reports nausea in pregnancy for 3 months; concern for postcoital bleeding after lifting | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2503, '2025-10-12 00:28:50', 1, 0, 27, 26, 35, 11, 11, 16, 15, 'HIST: medication: OCPs; hx of UTI in 2016 | CURR: notes pelvic pain that intermittent; concern for irregular cycles after lifting | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1282, '2025-10-12 00:28:50', 18, 27, 10, 21, 22, 2, 13, 18, 20, 'HIST: hx of fibroids in 2009; medication: OCPs | CURR: concern for pelvic pain after exercise; denies dysuria, but endorses postcoital bleeding weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1104, '2025-10-12 00:28:50', 7, 4, 3, 12, 48, 26, 11, 16, 14, 'HIST: hx of fibroids in 2020; prior C-section in 2024 | CURR: reports heavy periods for 6 months; concern for postcoital bleeding after intercourse | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1620, '2025-10-12 00:28:50', 5, 9, 67, 7, 11, 1, 14, 19, 9, 'HIST: prior laparoscopy in 2022; medication: metformin | CURR: reports pelvic pain for 6 months; notes leakage that worsens with menses | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2421, '2025-10-12 00:28:50', 7, 6, 54, 9, 22, 2, 14, 19, 20, 'HIST: prior myomectomy in 2015; family hx of endometrial cancer | CURR: denies dysuria, but endorses vaginal bulge daily; notes irregular cycles that worsens with menses | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1793, '2025-10-12 00:28:50', 30, 7, 42, 8, 10, 3, 14, 19, 17, 'HIST: hx of PCOS in 2024; prior LEEP in 2018 | CURR: reports urinary urgency for 1 year; concern for heavy periods after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1985, '2025-10-12 00:28:50', 10, 20, 6, 18, 38, 8, 11, 16, 1, 'HIST: prior myomectomy in 2017; medication: spironolactone | CURR: concern for vaginal bulge after intercourse; denies foul discharge, but endorses nausea in pregnancy daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2729, '2025-10-12 00:28:50', 10, 47, 16, 23, 3, 1, 13, 18, 8, 'HIST: hx of gestational diabetes in 2014; family hx of ovarian cancer | CURR: reports leakage for 6 months; notes irregular cycles that improves with NSAIDs | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2064, '2025-10-12 00:28:50', 6, 5, 51, 32, 4, 2, 14, 19, 0, 'HIST: family hx of ovarian cancer; prior myomectomy in 2022 | CURR: denies fever, but endorses urinary urgency twice weekly; reports leakage for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1675, '2025-10-12 00:28:50', 6, 9, 63, 1, 6, 15, 14, 19, 1, 'HIST: hx of endometriosis in 2021; prior LEEP in 2012 | CURR: denies fever, but endorses leakage weekly; concern for postcoital bleeding after exercise | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2052, '2025-10-12 00:28:50', 3, 18, 19, 23, 25, 12, 11, 16, 8, 'HIST: prior laparoscopy in 2023; medication: metformin | CURR: notes leakage that improves with NSAIDs; denies fever, but endorses urinary urgency twice weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1390, '2025-10-12 00:28:50', 1, 2, 14, 27, 39, 17, 11, 16, 1, 'HIST: medication: metformin; hx of endometriosis in 2024 | CURR: reports heavy periods for 3 months; denies dysuria, but endorses vaginal bulge twice weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1008, '2025-10-12 00:28:50', 15, 1, 33, 11, 30, 10, 14, 19, 5, 'HIST: hx of PCOS in 2021; family hx of ovarian cancer | CURR: concern for postcoital bleeding after intercourse; notes leakage that intermittent | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2247, '2025-10-12 00:28:50', 3, 27, 48, 5, 13, 4, 14, 19, 18, 'HIST: medication: spironolactone; family hx of breast cancer | CURR: notes urinary urgency that intermittent; denies foul discharge, but endorses vaginal bulge daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1736, '2025-10-12 00:28:50', 2, 24, 7, 15, 40, 12, 11, 16, 18, 'HIST: prior myomectomy in 2014; hx of fibroids in 2010 | CURR: reports irregular cycles for 2 weeks; notes postcoital bleeding that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1097, '2025-10-12 00:28:50', 17, 3, 14, 37, 18, 11, 5, 6, 0, 'HIST: medication: levonorgestrel IUD; prior laparoscopy in 2023 | CURR: denies dysuria, but endorses heavy periods daily; reports urinary urgency for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1365, '2025-10-12 00:28:50', 12, 44, 22, 12, 6, 4, 13, 18, 20, 'HIST: family hx of endometrial cancer; medication: spironolactone | CURR: notes leakage that worsens with menses; reports nausea in pregnancy for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1927, '2025-10-12 00:28:50', 12, 16, 54, 8, 3, 7, 14, 19, 4, 'HIST: prior myomectomy in 2008; family hx of breast cancer | CURR: notes leakage that occurs daily; reports leakage for 6 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2880, '2025-10-12 00:28:50', 17, 34, 9, 20, 18, 2, 13, 18, 1, 'HIST: prior myomectomy in 2008; hx of PCOS in 2024 | CURR: concern for nausea in pregnancy after intercourse; reports heavy periods for 6 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1621, '2025-10-12 00:28:50', 14, 8, 58, 4, 12, 4, 14, 19, 8, 'HIST: family hx of breast cancer; prior myomectomy in 2022 | CURR: reports leakage for 3 months; notes postcoital bleeding that worsens with menses | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1607, '2025-10-12 00:28:50', 11, 25, 5, 45, 9, 5, 9, 4, 0, 'HIST: medication: OCPs; family hx of endometrial cancer | CURR: concern for nausea in pregnancy after exercise; reports heavy periods for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1528, '2025-10-12 00:28:50', 7, 39, 14, 1, 32, 7, 13, 18, 0, 'HIST: family hx of breast cancer; medication: metformin | CURR: denies foul discharge, but endorses pelvic pain daily; reports postcoital bleeding for 2 weeks | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1371, '2025-10-12 00:28:50', 9, 9, 5, 20, 46, 11, 11, 16, 3, 'HIST: prior laparoscopy in 2021; family hx of breast cancer | CURR: notes urinary urgency that intermittent; reports heavy periods for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2215, '2025-10-12 00:28:50', 1, 43, 6, 37, 6, 7, 13, 18, 11, 'HIST: hx of gestational diabetes in 2014; family hx of ovarian cancer | CURR: reports heavy periods for 3 months; concern for nausea in pregnancy after lifting | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1725, '2025-10-12 00:28:50', 14, 17, 31, 21, 6, 11, 14, 19, 3, 'HIST: prior laparoscopy in 2020; family hx of endometrial cancer | CURR: notes vaginal bulge that intermittent; reports heavy periods for 3 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1669, '2025-10-12 00:28:50', 9, 24, 3, 8, 48, 8, 11, 16, 1, 'HIST: medication: spironolactone; family hx of endometrial cancer | CURR: concern for postcoital bleeding after childbirth 6 months ago; reports nausea in pregnancy for 3 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1061, '2025-10-12 00:28:50', 5, 34, 29, 15, 10, 7, 13, 18, 8, 'HIST: medication: metformin; hx of endometriosis in 2014 | CURR: concern for leakage after childbirth 6 months ago; reports urinary urgency for 2 weeks | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2265, '2025-10-12 00:28:50', 30, 9, 2, 5, 51, 3, 11, 16, 13, 'HIST: hx of PCOS in 2015; prior LEEP in 2018 | CURR: notes pelvic pain that improves with NSAIDs; denies dysuria, but endorses heavy periods daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2363, '2025-10-12 00:28:50', 26, 8, 40, 10, 8, 8, 14, 19, 6, 'HIST: medication: OCPs; hx of gestational diabetes in 2011 | CURR: reports nausea in pregnancy for 6 months; concern for vaginal bulge after exercise | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2378, '2025-10-12 00:28:50', 13, 24, 8, 12, 18, 25, 13, 18, 3, 'HIST: medication: spironolactone; hx of endometriosis in 2022 | CURR: notes heavy periods that worsens with menses; concern for postcoital bleeding after intercourse | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1123, '2025-10-12 00:28:50', 13, 3, 84, 0, 0, 0, 14, 19, 16, 'HIST: prior myomectomy in 2012; family hx of ovarian cancer | CURR: reports vaginal bulge for 6 months; concern for postcoital bleeding after intercourse | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1805, '2025-10-12 00:28:50', 3, 26, 2, 23, 28, 18, 11, 16, 1, 'HIST: hx of endometriosis in 2008; prior C-section in 2014 | CURR: denies foul discharge, but endorses urinary urgency weekly; concern for irregular cycles after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2935, '2025-10-12 00:28:50', 5, 3, 40, 24, 19, 9, 14, 19, 6, 'HIST: family hx of breast cancer; medication: metformin | CURR: notes postcoital bleeding that occurs daily; concern for postcoital bleeding after exercise | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2220, '2025-10-12 00:28:50', 36, 3, 35, 20, 1, 5, 12, 17, 15, 'HIST: hx of PCOS in 2023; family hx of ovarian cancer | CURR: concern for leakage after intercourse; notes urinary urgency that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1931, '2025-10-12 00:28:50', 17, 15, 54, 7, 7, 0, 14, 19, 20, 'HIST: prior LEEP in 2015; medication: metformin | CURR: denies fever, but endorses irregular cycles daily; reports leakage for 6 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2771, '2025-10-12 00:28:50', 19, 20, 12, 40, 1, 8, 10, 0, 7, 'HIST: prior myomectomy in 2024; medication: levonorgestrel IUD | CURR: denies foul discharge, but endorses heavy periods twice weekly; notes nausea in pregnancy that intermittent | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1273, '2025-10-12 00:28:50', 9, 11, 42, 6, 26, 6, 14, 19, 8, 'HIST: family hx of endometrial cancer; hx of UTI in 2008 | CURR: reports leakage for 1 year; notes vaginal bulge that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1135, '2025-10-12 00:28:50', 2, 0, 0, 31, 65, 2, 11, 16, 7, 'HIST: family hx of breast cancer; hx of fibroids in 2019 | CURR: reports heavy periods for 1 year; concern for urinary urgency after exercise | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1488, '2025-10-12 00:28:50', 8, 16, 1, 30, 32, 13, 11, 16, 15, 'HIST: family hx of endometrial cancer; hx of PCOS in 2022 | CURR: notes irregular cycles that worsens with menses; reports postcoital bleeding for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1508, '2025-10-12 00:28:50', 18, 7, 6, 11, 44, 14, 11, 16, 13, 'HIST: hx of endometriosis in 2021; medication: spironolactone | CURR: concern for urinary urgency after exercise; notes irregular cycles that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2513, '2025-10-12 00:28:50', 2, 22, 3, 43, 21, 9, 8, 6, 10, 'HIST: prior C-section in 2022; family hx of ovarian cancer | CURR: concern for irregular cycles after exercise; notes pelvic pain that intermittent | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2984, '2025-10-12 00:28:50', 6, 16, 38, 31, 6, 3, 14, 19, 6, 'HIST: family hx of breast cancer; prior LEEP in 2024 | CURR: denies fever, but endorses vaginal bulge twice weekly; concern for leakage after lifting | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2364, '2025-10-12 00:28:50', 7, 6, 23, 40, 19, 5, 6, 7, 1, 'HIST: prior C-section in 2015; medication: OCPs | CURR: reports pelvic pain for 6 months; denies foul discharge, but endorses leakage daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1184, '2025-10-12 00:28:50', 8, 7, 0, 41, 3, 41, 15, 20, 18, 'HIST: hx of UTI in 2013; prior C-section in 2019 | CURR: concern for heavy periods after lifting; notes irregular cycles that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2307, '2025-10-12 00:28:50', 20, 21, 28, 1, 13, 17, 14, 19, 15, 'HIST: family hx of ovarian cancer; hx of fibroids in 2024 | CURR: denies dysuria, but endorses urinary urgency daily; reports nausea in pregnancy for 6 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2583, '2025-10-12 00:28:50', 23, 0, 20, 8, 45, 4, 11, 16, 8, 'HIST: family hx of ovarian cancer; hx of PCOS in 2024 | CURR: denies fever, but endorses vaginal bulge weekly; concern for irregular cycles after exercise | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2078, '2025-10-12 00:28:50', 41, 3, 1, 3, 50, 2, 11, 16, 14, 'HIST: hx of PCOS in 2018; prior laparoscopy in 2014 | CURR: denies foul discharge, but endorses postcoital bleeding twice weekly; concern for pelvic pain after lifting | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1134, '2025-10-12 00:28:50', 29, 26, 15, 5, 11, 14, 12, 17, 16, 'HIST: prior LEEP in 2013; medication: levonorgestrel IUD | CURR: reports nausea in pregnancy for 3 months; notes irregular cycles that worsens with menses | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1177, '2025-10-12 00:28:50', 1, 13, 37, 27, 20, 2, 14, 19, 11, 'HIST: hx of UTI in 2011; family hx of ovarian cancer | CURR: notes heavy periods that occurs daily; reports leakage for 2 weeks | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1023, '2025-10-12 00:28:50', 3, 17, 41, 23, 12, 4, 14, 19, 7, 'HIST: prior LEEP in 2010; medication: spironolactone | CURR: concern for vaginal bulge after childbirth 6 months ago; reports vaginal bulge for 3 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1004, '2025-10-12 00:28:50', 10, 27, 12, 6, 27, 18, 11, 16, 1, 'HIST: family hx of ovarian cancer; hx of gestational diabetes in 2023 | CURR: notes urinary urgency that intermittent; denies fever, but endorses pelvic pain twice weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1339, '2025-10-12 00:28:50', 10, 17, 15, 21, 28, 9, 11, 16, 2, 'HIST: prior laparoscopy in 2010; family hx of ovarian cancer | CURR: notes nausea in pregnancy that occurs daily; reports vaginal bulge for 2 weeks | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1692, '2025-10-12 00:28:50', 10, 36, 16, 11, 12, 15, 13, 18, 15, 'HIST: hx of gestational diabetes in 2020; medication: OCPs | CURR: concern for vaginal bulge after exercise; denies dysuria, but endorses irregular cycles weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2432, '2025-10-12 00:28:50', 4, 5, 21, 2, 60, 8, 11, 16, 5, 'HIST: prior laparoscopy in 2018; medication: spironolactone | CURR: reports vaginal bulge for 1 year; notes irregular cycles that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1918, '2025-10-12 00:28:50', 9, 5, 65, 7, 7, 7, 14, 19, 9, 'HIST: medication: metformin; family hx of endometrial cancer | CURR: concern for irregular cycles after exercise; denies foul discharge, but endorses leakage weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2508, '2025-10-12 00:28:50', 3, 7, 11, 29, 47, 3, 11, 16, 14, 'HIST: prior laparoscopy in 2017; medication: levonorgestrel IUD | CURR: denies foul discharge, but endorses leakage weekly; concern for heavy periods after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1374, '2025-10-12 00:28:50', 22, 42, 4, 26, 4, 2, 13, 18, 2, 'HIST: prior C-section in 2008; hx of PCOS in 2016 | CURR: concern for nausea in pregnancy after intercourse; denies dysuria, but endorses pelvic pain daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1555, '2025-10-12 00:28:50', 16, 10, 14, 10, 22, 28, 15, 20, 17, 'HIST: medication: OCPs; prior C-section in 2011 | CURR: denies fever, but endorses vaginal bulge daily; concern for irregular cycles after exercise | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2319, '2025-10-12 00:28:50', 1, 14, 20, 23, 41, 1, 11, 16, 2, 'HIST: prior myomectomy in 2024; medication: spironolactone | CURR: reports urinary urgency for 1 year; denies foul discharge, but endorses pelvic pain daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2166, '2025-10-12 00:28:50', 2, 59, 3, 6, 24, 6, 13, 18, 11, 'HIST: family hx of endometrial cancer; hx of gestational diabetes in 2008 | CURR: denies fever, but endorses pelvic pain twice weekly; reports urinary urgency for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2758, '2025-10-12 00:28:50', 5, 52, 13, 9, 19, 2, 13, 18, 0, 'HIST: prior laparoscopy in 2025; medication: spironolactone | CURR: concern for nausea in pregnancy after lifting; reports urinary urgency for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2044, '2025-10-12 00:28:50', 13, 2, 21, 4, 57, 3, 11, 16, 6, 'HIST: prior C-section in 2013; medication: levonorgestrel IUD | CURR: notes pelvic pain that worsens with menses; reports leakage for 3 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2800, '2025-10-12 00:28:50', 28, 4, 49, 8, 8, 3, 14, 19, 20, 'HIST: family hx of endometrial cancer; hx of endometriosis in 2008 | CURR: concern for vaginal bulge after exercise; reports pelvic pain for 3 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2458, '2025-10-12 00:28:50', 5, 21, 20, 24, 16, 14, 10, 5, 3, 'HIST: prior laparoscopy in 2015; family hx of ovarian cancer | CURR: concern for nausea in pregnancy after exercise; denies foul discharge, but endorses leakage weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2271, '2025-10-12 00:28:50', 33, 6, 2, 16, 39, 4, 11, 16, 10, 'HIST: family hx of breast cancer; prior C-section in 2012 | CURR: notes pelvic pain that intermittent; denies foul discharge, but endorses postcoital bleeding daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2553, '2025-10-12 00:28:50', 6, 55, 4, 25, 1, 9, 13, 18, 12, 'HIST: prior LEEP in 2018; medication: metformin | CURR: notes irregular cycles that improves with NSAIDs; denies dysuria, but endorses nausea in pregnancy twice weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1327, '2025-10-12 00:28:50', 28, 2, 2, 29, 10, 29, 15, 20, 9, 'HIST: prior LEEP in 2016; hx of PCOS in 2013 | CURR: concern for heavy periods after exercise; reports urinary urgency for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1403, '2025-10-12 00:28:50', 22, 28, 32, 10, 1, 7, 14, 19, 5, 'HIST: hx of PCOS in 2013; prior C-section in 2011 | CURR: concern for vaginal bulge after lifting; denies foul discharge, but endorses nausea in pregnancy twice weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2737, '2025-10-12 00:28:50', 7, 8, 13, 30, 21, 21, 10, 3, 7, 'HIST: hx of fibroids in 2021; medication: spironolactone | CURR: concern for postcoital bleeding after lifting; denies dysuria, but endorses irregular cycles daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2901, '2025-10-12 00:28:50', 23, 2, 15, 12, 36, 12, 11, 16, 5, 'HIST: hx of endometriosis in 2019; family hx of endometrial cancer | CURR: notes vaginal bulge that worsens with menses; denies fever, but endorses pelvic pain daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1685, '2025-10-12 00:28:50', 34, 15, 5, 14, 25, 7, 12, 17, 0, 'HIST: prior myomectomy in 2010; medication: spironolactone | CURR: concern for postcoital bleeding after intercourse; denies fever, but endorses pelvic pain weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1167, '2025-10-12 00:28:50', 16, 7, 22, 22, 29, 4, 11, 16, 15, 'HIST: prior laparoscopy in 2016; family hx of breast cancer | CURR: reports urinary urgency for 1 year; concern for urinary urgency after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2305, '2025-10-12 00:28:50', 11, 15, 25, 22, 6, 21, 14, 19, 7, 'HIST: prior C-section in 2018; medication: metformin | CURR: concern for leakage after intercourse; denies fever, but endorses leakage weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2548, '2025-10-12 00:28:50', 23, 4, 7, 11, 18, 37, 15, 20, 16, 'HIST: family hx of endometrial cancer; prior myomectomy in 2010 | CURR: notes urinary urgency that improves with NSAIDs; reports pelvic pain for 2 weeks | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2614, '2025-10-12 00:28:50', 15, 42, 16, 12, 11, 4, 13, 18, 9, 'HIST: family hx of ovarian cancer; medication: levonorgestrel IUD | CURR: notes urinary urgency that worsens with menses; concern for heavy periods after intercourse | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2927, '2025-10-12 00:28:50', 34, 4, 24, 16, 7, 15, 12, 17, 16, 'HIST: family hx of breast cancer; hx of fibroids in 2014 | CURR: concern for urinary urgency after exercise; notes leakage that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2915, '2025-10-12 00:28:50', 9, 2, 28, 43, 12, 6, 0, 4, 3, 'HIST: prior C-section in 2014; medication: OCPs | CURR: concern for irregular cycles after exercise; denies foul discharge, but endorses vaginal bulge daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1230, '2025-10-12 00:28:50', 5, 9, 3, 24, 5, 54, 15, 20, 12, 'HIST: family hx of endometrial cancer; medication: OCPs | CURR: notes postcoital bleeding that improves with NSAIDs; denies foul discharge, but endorses irregular cycles twice weekly | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2707, '2025-10-12 00:28:50', 2, 5, 31, 57, 2, 3, 0, 7, 4, 'HIST: medication: levonorgestrel IUD; prior myomectomy in 2022 | CURR: concern for urinary urgency after intercourse; reports leakage for 1 year | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2688, '2025-10-12 00:28:50', 13, 4, 31, 5, 35, 12, 11, 16, 9, 'HIST: hx of endometriosis in 2016; family hx of endometrial cancer | CURR: denies fever, but endorses vaginal bulge twice weekly; notes leakage that intermittent | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1177, '2025-10-12 00:28:50', 54, 3, 25, 10, 8, 0, 12, 17, 18, 'HIST: hx of PCOS in 2021; medication: OCPs | CURR: reports irregular cycles for 3 months; notes vaginal bulge that improves with NSAIDs | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2433, '2025-10-12 00:28:50', 6, 3, 54, 23, 7, 7, 14, 19, 0, 'HIST: medication: metformin; family hx of ovarian cancer | CURR: denies foul discharge, but endorses postcoital bleeding twice weekly; notes leakage that intermittent | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2363, '2025-10-12 00:28:50', 16, 4, 2, 55, 17, 6, 0, 4, 8, 'HIST: family hx of endometrial cancer; medication: metformin | CURR: denies foul discharge, but endorses heavy periods daily; concern for heavy periods after exercise | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2758, '2025-10-12 00:28:50', 13, 7, 6, 53, 20, 1, 4, 10, 2, 'HIST: family hx of breast cancer; hx of PCOS in 2014 | CURR: notes heavy periods that improves with NSAIDs; concern for irregular cycles after intercourse | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2991, '2025-10-12 00:28:50', 0, 26, 6, 31, 34, 3, 11, 16, 13, 'HIST: family hx of endometrial cancer; prior laparoscopy in 2012 | CURR: reports nausea in pregnancy for 1 year; concern for heavy periods after lifting | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 2472, '2025-10-12 00:28:50', 6, 52, 1, 9, 17, 15, 13, 18, 11, 'HIST: family hx of breast cancer; medication: spironolactone | CURR: reports pelvic pain for 3 months; notes nausea in pregnancy that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1078, '2025-10-12 00:28:50', 17, 1, 12, 27, 29, 14, 11, 16, 14, 'HIST: prior laparoscopy in 2025; family hx of ovarian cancer | CURR: reports heavy periods for 3 months; concern for vaginal bulge after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 1706, '2025-10-12 00:28:51', 0, 6, 13, 13, 27, 41, 15, 20, 16, 'HIST: prior myomectomy in 2014; hx of endometriosis in 2012 | CURR: denies foul discharge, but endorses vaginal bulge daily; concern for vaginal bulge after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2760, '2025-10-12 00:28:51', 34, 0, 10, 5, 31, 20, 12, 17, 0, 'HIST: hx of PCOS in 2022; prior laparoscopy in 2018 | CURR: denies dysuria, but endorses postcoital bleeding daily; notes urinary urgency that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2285, '2025-10-12 00:28:51', 2, 11, 4, 16, 45, 22, 11, 16, 13, 'HIST: prior LEEP in 2010; hx of UTI in 2019 | CURR: denies dysuria, but endorses pelvic pain weekly; concern for urinary urgency after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1676, '2025-10-12 00:28:51', 19, 34, 13, 5, 9, 20, 13, 18, 2, 'HIST: family hx of breast cancer; hx of fibroids in 2013 | CURR: notes urinary urgency that occurs daily; concern for irregular cycles after childbirth 6 months ago | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (103, 1369, '2025-10-12 00:28:51', 4, 7, 63, 2, 11, 13, 14, 19, 3, 'HIST: family hx of endometrial cancer; hx of UTI in 2016 | CURR: concern for leakage after exercise; reports pelvic pain for 3 months | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 1207, '2025-10-12 00:28:51', 6, 8, 41, 22, 9, 14, 14, 19, 1, 'HIST: prior myomectomy in 2025; medication: metformin | CURR: denies foul discharge, but endorses vaginal bulge twice weekly; notes heavy periods that improves with NSAIDs | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (102, 2737, '2025-10-12 00:28:51', 22, 3, 41, 8, 26, 0, 14, 19, 16, 'HIST: family hx of endometrial cancer; hx of UTI in 2008 | CURR: concern for leakage after exercise; notes leakage that occurs daily | Q/A steps: 3', FALSE, NULL);
INSERT INTO triage (agent_id, client_id, date_time, re_conf, mfm_conf, uro_conf, gob_conf, mis_conf, go_conf, doc_id1, doc_id2, doc_id3, agent_notes, sent_to_epic, epic_sent_date) VALUES (101, 2173, '2025-10-12 00:28:51', 14, 18, 1, 23, 44, 0, 11, 16, 19, 'HIST: prior LEEP in 2012; family hx of endometrial cancer | CURR: notes urinary urgency that worsens with menses; reports pelvic pain for 3 months | Q/A steps: 3', FALSE, NULL);
