
CREATE TABLE IF NOT EXISTS triage_question (
    triage_question_id SERIAL PRIMARY KEY,
    triage_id INT NOT NULL REFERENCES triage(triage_id),
    triage_question VARCHAR(256),
    triage_answer VARCHAR(1024)
);

INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (1, 'Are you currently pregnant or recently postpartum?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (2, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (3, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (4, 'Have you been trying to conceive for more than 12 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (5, 'Are you currently pregnant or recently postpartum?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (6, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (7, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (8, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (9, 'Have you been trying to conceive for more than 12 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (10, 'Have you had pelvic pain for more than 3 months?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (11, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (12, 'Are you currently pregnant or recently postpartum?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (13, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (14, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (15, 'Have you had pelvic pain for more than 3 months?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (16, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (17, 'Are you currently pregnant or recently postpartum?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (18, 'Have you experienced urinary leakage with coughing or exercise?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (19, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (20, 'Are you currently pregnant or recently postpartum?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (21, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (22, 'Have you been trying to conceive for more than 12 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (23, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (24, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (25, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (26, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (27, 'Are you currently pregnant or recently postpartum?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (28, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (29, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (30, 'Have you been trying to conceive for more than 12 months?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (31, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (32, 'Are you currently pregnant or recently postpartum?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (33, 'Have you had pelvic pain for more than 3 months?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (34, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (35, 'Are you currently pregnant or recently postpartum?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (36, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (37, 'Have you experienced urinary leakage with coughing or exercise?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (38, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (39, 'Have you experienced urinary leakage with coughing or exercise?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (40, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (41, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (42, 'Are you currently pregnant or recently postpartum?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (43, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (44, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (45, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (46, 'Have you experienced urinary leakage with coughing or exercise?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (47, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (48, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (49, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (50, 'Have you had pelvic pain for more than 3 months?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (51, 'Have you experienced urinary leakage with coughing or exercise?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (52, 'Are you currently pregnant or recently postpartum?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (53, 'Have you experienced urinary leakage with coughing or exercise?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (54, 'Have you had pelvic pain for more than 3 months?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (55, 'Have you been trying to conceive for more than 12 months?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (56, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (57, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (58, 'Have you had pelvic pain for more than 3 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (59, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (60, 'Have you been trying to conceive for more than 12 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (61, 'Have you had pelvic pain for more than 3 months?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (62, 'Have you experienced urinary leakage with coughing or exercise?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (63, 'Have you experienced urinary leakage with coughing or exercise?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (64, 'Are you currently pregnant or recently postpartum?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (65, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (66, 'Have you been trying to conceive for more than 12 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (67, 'Are you currently pregnant or recently postpartum?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (68, 'Have you had pelvic pain for more than 3 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (69, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (70, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (71, 'Have you experienced urinary leakage with coughing or exercise?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (72, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (73, 'Have you been trying to conceive for more than 12 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (74, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (75, 'Have you had pelvic pain for more than 3 months?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (76, 'Are you currently pregnant or recently postpartum?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (77, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (78, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (79, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (80, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (81, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (82, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (83, 'Have you been trying to conceive for more than 12 months?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (84, 'Any history of cancer, BRCA mutation, or suspicious ovarian mass on imaging?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (85, 'Have you experienced urinary leakage with coughing or exercise?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (86, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (87, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (88, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (89, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (90, 'Have you experienced urinary leakage with coughing or exercise?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (91, 'Have you had pelvic pain for more than 3 months?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (92, 'Have you noted a vaginal bulge or pressure that worsens by day''s end?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (93, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (94, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (95, 'Are you currently pregnant or recently postpartum?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (96, 'Have you experienced urinary leakage with coughing or exercise?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (97, 'Are you currently pregnant or recently postpartum?', '1 (yes)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (98, 'Any abnormal bleeding between periods or post-menopausal bleeding?', '0 (no)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (99, 'Have you experienced urinary leakage with coughing or exercise?', '-1 (skip)');
INSERT INTO triage_question (triage_id, triage_question, triage_answer) VALUES (100, 'Any prior pelvic surgery (laparoscopy, myomectomy, hysterectomy)?', '1 (yes)');
